from tkinter import *   
import tkinter as tk
from tkinter import ttk
import pandas as pd
import rlcompleter,readline

#readline.parse_and_bind('tab:complete')
#entry1.bind('<Keypress-Tab>',fun1)
def go_1(*args):
    a=comboxlist.get()
    print('a:\n',a)
def go(*args):
    a=comboxlist.get()
    #print('a:\n',a)
    
    if a=='Startpoint':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Startpoint_frame.grid(row=3,column=0)
        botton_search.grid(row=5,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=6,column=0)
    elif a=='Endpoint':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Endpoint_frame.grid(row=3,column=0)
        botton_search.grid(row=5,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=6,column=0)
    elif a=='Timing_slack':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Timing_slack_fram.grid(row=3,column=0)
        botton_search.grid(row=5,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=6,column=0)
    elif a=='clock_group':  
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget() 
        lb.grid_forget() 
        clock_group_fram.grid(row=3,column=0)
        botton_search.grid(row=5,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=6,column=0)
    elif a=='Startpoint&Endpoint':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Startpoint_frame.grid(row=3,column=0)
        Endpoint_frame.grid(row=4,column=0)
        botton_search.grid(row=6,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=7,column=0)
    elif a=='Startpoint&Timing_slack':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Startpoint_frame.grid(row=3,column=0)
        Timing_slack_fram.grid(row=4,column=0)
        botton_search.grid(row=6,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=7,column=0)
    elif a=='Startpoint&clock_group':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Startpoint_frame.grid(row=3,column=0)
        clock_group_fram.grid(row=4,column=0)
        botton_search.grid(row=6,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=7,column=0)
    elif a=='Endpoint&Timing_slack':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Endpoint_frame.grid(row=3,column=0)
        Timing_slack_fram.grid(row=4,column=0)
        botton_search.grid(row=6,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=7,column=0)
    elif a=='Endpoint&clock_group':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Endpoint_frame.grid(row=3,column=0)
        clock_group_fram.grid(row=4,column=0)
        botton_search.grid(row=6,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=7,column=0)
    elif a=='Timing_slack&clock_group':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Timing_slack_fram.grid(row=3,column=0)
        clock_group_fram.grid(row=4,column=0)
        botton_search.grid(row=6,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=7,column=0)
    elif a=='Startpoint&Endpoint&Timing_slack':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Startpoint_frame.grid(row=3,column=0)
        Endpoint_frame.grid(row=4,column=0)
        Timing_slack_fram.grid(row=5,column=0)
        botton_search.grid(row=8,column=0) 
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0) 
        #listbox_frame.grid(row=9,column=0)    
    elif a=='Startpoint&Endpoint&clock_group':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Startpoint_frame.grid(row=3,column=0)
        Endpoint_frame.grid(row=4,column=0)
        clock_group_fram.grid(row=5,column=0)
        botton_search.grid(row=8,column=0) 
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0) 
        #listbox_frame.grid(row=9,column=0)      
    elif a=='Startpoint&Timing_slack&clock_group':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Startpoint_frame.grid(row=3,column=0)
        Timing_slack_fram.grid(row=4,column=0)
        clock_group_fram.grid(row=5,column=0)
        botton_search.grid(row=8,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=9,column=0)
    elif a=='Endpoint&Timing_slack&clock_group':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Endpoint_frame.grid(row=3,column=0)
        Timing_slack_fram.grid(row=4,column=0)
        clock_group_fram.grid(row=5,column=0)
        botton_search.grid(row=8,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=9,column=0)   
    elif a=='Startpoint&Endpoint&Timing_slack&clock_group':
        Startpoint_frame.grid_forget()
        Endpoint_frame.grid_forget()
        Timing_slack_fram.grid_forget()
        clock_group_fram.grid_forget()
        botton_search.grid_forget()
        lb.grid_forget()
        Startpoint_frame.grid(row=3,column=0)
        Endpoint_frame.grid(row=4,column=0)
        Timing_slack_fram.grid(row=5,column=0)
        clock_group_fram.grid(row=6,column=0)
        botton_search.grid(row=10,column=0)
        comboxlist_Startpoint.current(0)
        comboxlist_Endpoint.current(0)
        comboxlist_Timing_slack.current(0)
        comboxlist_clock_group.current(0)
        #listbox_frame.grid(row=15,column=0)


root = Tk()
root.title("画个锤子")
root.geometry("1000x500")

section_3=Frame(root,height=1000,width=500)
section_1=Frame(root,height=250,width=500,bg='red')
section_2=Frame(root,height=250,width=500,bg='green')

label_Startpoint=Label(section_3,text="Startpoint")
label_3=Label(section_3,text="This is the search section:")

botton_search=Button(section_3,text='Search')

comvalue=tk.StringVar()
comboxlist=ttk.Combobox(section_3,state='readonly',textvariable=comvalue,width=40)
comboxlist['values']=('Startpoint','Endpoint','Timing_slack','clock_group',
                    'Startpoint&Endpoint','Startpoint&Timing_slack','Startpoint&clock_group',
                    'Endpoint&Timing_slack','Endpoint&clock_group',
                    'Timing_slack&clock_group','Startpoint&Endpoint&Timing_slack',
                    'Startpoint&Endpoint&clock_group','Startpoint&Timing_slack&clock_group',
                    'Endpoint&Timing_slack&clock_group',
                    'Startpoint&Endpoint&Timing_slack&clock_group')
comboxlist.bind('<<ComboboxSelected>>',go)

label_3.grid(row=0,column=0)
comboxlist.grid(row=1,column=0)

def refresh(event):
    print(1)
Startpoint=['',1,2,3]
Endpoint=['',2,3,4]
Timing_slack=['',3,4,5]
clock_group=['',4,5,6]
#------Startpoint_frame----------
Startpoint_frame=Frame(section_3,height=500,width=500)
label_Startpoint=Label(Startpoint_frame,text="    Startpoint")
label_Startpoint.grid(row=1,column=0,sticky='N')
comvalue_Startpoint=tk.StringVar()
comboxlist_Startpoint=ttk.Combobox(Startpoint_frame,state='readonly',textvariable=comvalue_Startpoint,width=40)
comboxlist_Startpoint['values']=(Startpoint)
comboxlist_Startpoint.bind('<<ComboboxSelected>>',go_1)
comboxlist_Startpoint.grid(row=1,column=1)
#------Endpoint_frame----------
Endpoint_frame=Frame(section_3,height=500,width=500)
label_Startpoint=Label(Endpoint_frame,text="      Endpoint")
label_Startpoint.grid(row=1,column=0,sticky='N')
comvalue_Endpoint=tk.StringVar()
comboxlist_Endpoint=ttk.Combobox(Endpoint_frame,state='readonly',textvariable=comvalue_Endpoint,width=40)
comboxlist_Endpoint['values']=(Endpoint)
comboxlist_Endpoint.bind('<<ComboboxSelected>>',go_1)
comboxlist_Endpoint.grid(row=1,column=1)
#------Timing_slack_fram----------
Timing_slack_fram=Frame(section_3,height=500,width=500)
label_Startpoint=Label(Timing_slack_fram,text="Timing_slack")
label_Startpoint.grid(row=1,column=0)
comvalue_Timing_slack=tk.StringVar()
comboxlist_Timing_slack=ttk.Combobox(Timing_slack_fram,state='readonly',textvariable=comvalue_Timing_slack,width=40)
comboxlist_Timing_slack['values']=(Timing_slack)
comboxlist_Timing_slack.bind('<<ComboboxSelected>>',go_1)
comboxlist_Timing_slack.grid(row=1,column=1)
#------clock_group----------                                              
clock_group_fram=Frame(section_3,height=500,width=500)
label_Startpoint=Label(clock_group_fram,text=" clock_group")
label_Startpoint.grid(row=1,column=0)
comvalue_clock_group=tk.StringVar()
comboxlist_clock_group=ttk.Combobox(clock_group_fram,state='readonly',textvariable=comvalue_clock_group,width=40)
comboxlist_clock_group['values']=(clock_group)
comboxlist_clock_group.bind('<<ComboboxSelected>>',go_1)
comboxlist_clock_group.grid(row=1,column=1)
#-----listbox----
listbox_frame=Frame(section_3,height=500,width=500)
scrollbar = Scrollbar(listbox_frame)  
scrollbar.pack(side=RIGHT, fill=Y)
#scrollbar_1 = Scrollbar(listbox_frame)  
#scrollbar_1.pack(side=BOTTOM, fill=X)
lb=Listbox(listbox_frame,yscrollcommand=scrollbar.set)
scrollbar.config(command=lb.yview)
#scrollbar_1.config(command=lb.xview)
lb.pack(side=LEFT, fill=BOTH)

Startpoint=[1,2,3]
Endpoint=[2,3,4]
Timing_slack=[3,4,5]
clock_group=[4,5,6]
for item in Startpoint:
    lb.insert(END,item)   
 




section_3.pack(side=LEFT)
section_3.pack_propagate(False)
section_1.pack(anchor=NE)
section_1.pack_propagate(False)
section_2.pack(anchor=NE)
section_2.pack_propagate(False)



root.mainloop()